site: 
  title: Horizon
  start_page: horizon::index.adoc
content: 
  sources: 
  - url: .
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: /antora/ui-bundle.zip
asciidoc:
  attributes:
    experimental: true
    stem: latexmath
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    source-language: asciidoc@
    distribution: 'Horizon'
    tabs: tabs
  extensions:
    - ./docs/lib/tabs-block.js
output: 
  clean: true
  dir: ./public 
  destinations: 
  - provider: fs
  - provider: archive
